# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Vericode Scan

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
      
    - name: Zip up package 
      run: |
            cd ..
            ls -R
            echo "-------------"
            tar --exclude .git -zcvf package.tar.gz lvfs/
            echo "-------------"
            ls -R
            mv package.tar.gz lvfs/
        
    - name: Veracode Upload And Scan
      uses: veracode/veracode-uploadandscan-action@master
      with:
        appname: Data Science - lvfs
        createprofile: true
        createsandbox: true
        version: ${{ github.run_id }}
        filepath: package.tar.gz
        sandboxname: Github-Sandbox
        vid: ${{ secrets.VERACODE_API_ID }}
        vkey: ${{ secrets.VERACODE_API_KEY }}
